// Original recipes. Source labels document the researched function, not endorsement.
const text = (id, label, value = '') => ({ id, label, type: 'text', default: value });
const area = (id, label, value = '') => ({ id, label, type: 'textarea', default: value });
const select = (id, label, options, value = options[0]) => ({ id, label, type: 'select', default: value, options });
const number = (id, label, value, min, max) => ({ id, label, type: 'number', default: value, min, max });
const style = () => select('style', 'Visual direction', ['cinematic', 'illustrated', 'photographic', 'manga', 'editorial']);
const camera = () => select('camera', 'Camera movement', ['locked', 'slow push', 'orbit', 'tracking', 'handheld']);
const mood = () => select('mood', 'Mood', ['playful', 'calm', 'dramatic', 'dreamlike', 'bold']);
const template = (id, title, sourceTemplate, category, icon, accent, description, promptTemplate, fields, extra = {}) => ({
  id, title, sourceTemplate, category, icon, accent, description, promptTemplate, fields,
  runtime: 'studio', studioMode: category === 'video' ? 'video' : category === 'writing' ? 'story' : 'image',
  tags: [category, 'recipe'], ...extra,
  executionKind: category === 'writing' ? 'local-model' : extra.runtime === 'local' ? 'browser' : 'studio-guided',
});

export const catalog = [
  template('sketch-to-scene', 'Sketch to Scene', 'Simple Sketch', 'image', 'pencil', '#f2b96d',
    'Turn a selected drawing into a finished image with your chosen visual direction.',
    'Develop the selected sketch into a finished image. Preserve its composition and recognizable shapes. Visual direction: {{style}}. Material: {{material}}.',
    [style(), text('material', 'Material or finish', 'soft clay')], { tags: ['image', 'sketch', 'materials'] }),
  template('world-finder', 'World Finder', 'Scene Explorer', 'image', 'compass', '#a8cfef',
    'Explore a setting through atmosphere, architecture and a consistent visual world.',
    'Create an establishing image of the requested setting. Time: {{time}}. Atmosphere: {{mood}}. Visual direction: {{style}}. Include believable environmental detail.',
    [select('time', 'Time of day', ['golden hour', 'daylight', 'blue hour', 'night']), mood(), style()]),
  template('mockup-maker', 'Mockup Maker', 'Mockup', 'image', 'monitor', '#c7caa9',
    'Fit a selected design into a clean canvas layout, ready to export locally.',
    'Prepare a clean presentation canvas for the selected design. Ratio: {{ratio}}. Fit: {{fit}}. Background: {{background}}.',
    [select('ratio', 'Canvas ratio', ['1:1', '16:9', '9:16', '4:5', 'original']), number('width', 'Custom width', 1600, 1, 4096), number('height', 'Custom height', 1600, 1, 4096), select('fit', 'Image fit', ['contain', 'cover']), text('background', 'Background color', '#101312')],
    { runtime: 'local', localOperation: 'image-resize', tags: ['image', 'layout', 'local'] }),
  template('image-finish', 'Image Finish', 'Image Editor', 'image', 'sliders', '#ddb0c3',
    'Give an image a restrained color finish with a live preview and local export.',
    'Apply a {{preset}} color finish at {{intensity}} percent intensity to the selected image.',
    [select('preset', 'Color finish', ['original', 'noir', 'warm', 'cool', 'punchy'], 'warm'), number('intensity', 'Intensity', 100, 0, 100)],
    { runtime: 'local', localOperation: 'image-filter', tags: ['image', 'color', 'local'] }),
  template('shot-atlas', 'Shot Atlas', 'Shot Explorer', 'image', 'camera', '#a9c3dd',
    'Plan alternate camera angles while keeping your subject and setting consistent.',
    'Explore the selected subject with a {{shot}} camera shot and {{lens}} lens feel. Keep identity, clothing and setting consistent with the reference.',
    [select('shot', 'Shot', ['wide', 'medium', 'close-up', 'low angle', 'overhead']), select('lens', 'Lens feel', ['35mm', '50mm', '85mm', 'wide cinematic'])]),
  template('select-and-replace', 'Select & Replace', 'Mask Magic', 'image', 'scan', '#b8d9ce',
    'Describe a precise regional edit for Image Studio using your selected reference.',
    'Edit only this requested region: {{region}}. Replacement: {{replacement}}. Preserve all other image content, lighting and perspective. Ask for a region selection if the target is ambiguous.',
    [text('region', 'Region to edit', 'background'), area('replacement', 'Replace with', 'a sunlit garden')]),
  template('reference-blend', 'Reference Blend', 'Converge', 'image', 'layers', '#d5bdde',
    'Combine reference directions into one coherent composition rather than a collage.',
    'Blend the selected references into one coherent image. Composition priority: {{priority}}. Visual direction: {{style}}. Preserve the requested subject identity.',
    [text('priority', 'What to preserve', 'subject from the first reference, atmosphere from the second'), style()]),
  template('image-grid', 'Image Grid', 'Grid Architect', 'image', 'grid', '#b6d78d',
    'Arrange up to eight selected images into a polished contact sheet on your device.',
    'Arrange selected images in {{columns}} columns with {{gap}} pixel gutters on {{background}}.',
    [number('columns', 'Columns', 2, 1, 4), number('gap', 'Gutter', 16, 0, 80), text('background', 'Background color', '#101312')],
    { runtime: 'local', localOperation: 'image-grid', tags: ['image', 'layout', 'local'] }),

  template('motion-finish', 'Motion Finish', 'Shader Effects', 'video', 'sparkles', '#a9bfda',
    'Prepare a restrained effect direction for a clip in the editor.',
    'Prepare an editor workflow for the selected clip with {{effect}} effects at {{intensity}} intensity. Preserve duration, audio and subject clarity. Preview before exporting.',
    [select('effect', 'Effect', ['film grain', 'soft bloom', 'chromatic fringe', 'halftone']), select('intensity', 'Strength', ['subtle', 'medium', 'bold'])], { studioMode: 'editor', tags: ['video', 'effects', 'editor'] }),
  template('title-frame', 'Title Frame', 'Type Overlays', 'video', 'type', '#edb4bd',
    'Add a readable title to a selected still or poster with an immediate local preview.',
    'Place the title {{title}} at {{position}}, with {{fontSize}} pixel type in {{color}}.',
    [text('title', 'Title', 'Make something remarkable.'), number('fontSize', 'Type size', 64, 12, 240), text('color', 'Text color', '#ffffff'), select('position', 'Position', ['top', 'center', 'bottom'], 'bottom')],
    { runtime: 'local', localOperation: 'type-overlay', studioMode: 'editor', tags: ['video', 'typography', 'local still'] }),
  template('pixel-layout', 'Pixel Layout', 'pixelBento', 'video', 'layout', '#b4bddc',
    'Design a modular moving layout from selected clips and images.',
    'Design a bento-grid montage using selected assets. Layout: {{layout}}. Pace: {{pace}}. Maintain safe gutters and avoid cropping faces. Prepare the edit in Editor Studio.',
    [select('layout', 'Layout', ['three panels', 'four panels', 'hero and details']), select('pace', 'Pace', ['gentle', 'rhythmic', 'energetic'])], { studioMode: 'editor' }),
  template('poster-lab', 'Poster Lab', 'Poster Designer', 'video', 'image', '#e8c38e',
    'Build an expressive key-art poster with clear hierarchy and space for a title.',
    'Create key art for the requested story or campaign. Format: {{format}}. Visual direction: {{style}}. Reserve deliberate negative space for the title: {{title}}. Keep important artwork inside safe margins.',
    [text('title', 'Poster title', 'A new beginning'), select('format', 'Format', ['portrait poster', 'square cover', 'wide banner']), style()], { studioMode: 'image' }),
  template('sketch-to-motion', 'Sketch to Motion', 'Video Sketch', 'video', 'pencil', '#b7d7c7',
    'Use a selected sketch as a composition guide for a short animated shot.',
    'Animate the selected sketch into a short shot. Action: {{action}}. Camera: {{camera}}. Preserve composition and character identity. Visual direction: {{style}}.',
    [text('action', 'Action', 'a gentle breeze moves through the scene'), camera(), style()]),
  template('transition-lab', 'Transition Lab', 'Transition Machine', 'video', 'shuffle', '#d8b5db',
    'Plan a coherent visual bridge between two selected moments.',
    'Create a transition between the selected first and last frames. Technique: {{transition}}. Duration feel: {{pace}}. Keep spatial continuity; avoid unwanted new subjects.',
    [select('transition', 'Technique', ['match cut', 'camera move', 'light wipe', 'morph']), select('pace', 'Timing', ['quick', 'gentle', 'slow cinematic'])]),
  template('dream-signal', 'Dream Signal', 'Weirdcore', 'video', 'orbit', '#b6a7d9',
    'Explore surreal motion with a clear subject and intentional visual atmosphere.',
    'Create a dreamlike scene using {{motif}} motifs. Mood: {{mood}}. Camera: {{camera}}. Keep it non-graphic and visually coherent.',
    [text('motif', 'Surreal motif', 'floating doors and impossible staircases'), mood(), camera()]),
  template('frame-fit', 'Frame Fit', 'Video Resizer', 'video', 'maximize', '#a2cec1',
    'Prepare a clip for a new aspect ratio with subject-aware framing in the editor.',
    'Prepare a resize workflow for selected clips to {{ratio}} with {{fit}} framing. Preserve important faces and on-screen text. Keep original duration and audio. Preview the crop in Editor Studio before export.',
    [select('ratio', 'Output ratio', ['9:16', '16:9', '1:1', '4:5']), select('fit', 'Framing', ['subject-aware crop', 'letterbox', 'blurred background'])], { studioMode: 'editor' }),
  template('rough-cut', 'Rough Cut', 'Stringout Creator', 'video', 'film', '#c8d89e',
    'Turn selected shots into a sensible first edit with a beginning, middle and ending.',
    'Organize selected clips into a rough cut. Structure: {{structure}}. Pace: {{pace}}. Preserve source audio and use only selected media. Mark missing beats rather than inventing unavailable footage.',
    [select('structure', 'Structure', ['chronological', 'setup reveal payoff', 'montage']), select('pace', 'Pace', ['calm', 'balanced', 'fast'])], { studioMode: 'editor' }),
  template('rhythm-cut', 'Rhythm Cut', 'Video Granulator', 'video', 'music', '#deb9a0',
    'Create a rhythm-first edit direction from short fragments of your footage.',
    'Prepare a rhythmic edit from selected footage with {{rhythm}} pacing. Fragment length: {{length}}. Retain recognizable key moments and avoid flashing effects. Use Editor Studio for review and export.',
    [select('rhythm', 'Rhythm', ['even pulse', 'rising energy', 'syncopated']), select('length', 'Fragment length', ['short', 'medium', 'mixed'])], { studioMode: 'editor' }),

  template('cast-notes', 'Cast Notes', 'Character X-Ray', 'writing', 'user', '#bdd5a9',
    'Use an installed local model to write a consistent character bible and visual direction.',
    'Create a character bible. Character: {{character}}. Role: {{role}}. Include motivation, strengths, limitations, visual identifiers and consistency notes. Do not infer sensitive personal traits from images.',
    [area('character', 'Character', 'a curious courier with a secret'), select('role', 'Story role', ['protagonist', 'supporting character', 'antagonist', 'ensemble'])], { runtime: 'local', localOperation: 'prompt-builder', studioMode: 'character', tags: ['writing', 'characters', 'prompt'] }),
  template('style-brief', 'Style Brief', 'Style Writer', 'writing', 'palette', '#d4badd',
    'Use an installed local model to write art direction with concrete lighting and composition notes.',
    'Write an art direction brief for {{subject}} in {{style}} form. Mood: {{mood}}. Include palette, line or material treatment, lighting, composition and things to avoid.',
    [text('subject', 'Project', 'an illustrated adventure'), style(), mood()], { runtime: 'local', localOperation: 'prompt-builder', studioMode: 'image', tags: ['writing', 'style', 'prompt'] }),
  template('storyboard-builder', 'Storyboard Builder', 'Storyboard Studio', 'writing', 'panels', '#b3cdda',
    'Use an installed local model to write sequential scenes, shot choices, dialogue and an emotional arc.',
    'Plan a storyboard with {{scenes}} scenes. Story form: {{form}}. Include each scene purpose, action, camera framing, dialogue and sound direction. Maintain continuity and end with a clear payoff.',
    [number('scenes', 'Scenes', 3, 2, 12), select('form', 'Story form', ['short film', 'comic chapter', 'animated storybook'])], { runtime: 'local', localOperation: 'prompt-builder', tags: ['writing', 'storyboard', 'prompt'] }),
  template('prompt-branches', 'Prompt Branches', 'Prompt Tree', 'writing', 'git-branch', '#c7d997',
    'Use an installed local model to develop distinct creative directions while retaining the core idea.',
    'Develop {{branches}} distinct creative directions for the brief. Vary {{axis}} while preserving the central subject and goal. Give each direction a concise prompt and explain its visual difference.',
    [number('branches', 'Directions', 3, 2, 6), select('axis', 'Explore', ['visual style', 'setting', 'tone', 'camera framing'])], { runtime: 'local', localOperation: 'prompt-builder', studioMode: 'image', tags: ['writing', 'ideas', 'prompt'] }),
  template('story-seed', 'Story Seed', 'Story Sketch', 'writing', 'book', '#dec7a5',
    'Use an installed local model to develop cast, chapters and an achievable story production plan.',
    'Develop a story proposal in {{form}} form for {{audience}}. Include premise, cast, setting, chapter outline and visual direction: {{style}}. Preserve requested character names and explain production needs.',
    [select('form', 'Story form', ['manga', 'colour storybook', 'western comic', 'animated storybook']), text('audience', 'Audience', 'all ages'), style()], { runtime: 'local', localOperation: 'prompt-builder', tags: ['writing', 'story', 'prompt'] }),

  template('frame-study', 'Frame Study', 'Frame Deconstructor', 'experimental', 'scan', '#c1cad7',
    'Analyze visual construction and translate it into an actionable shot brief.',
    'Study the selected frame for composition, lighting, depth, camera angle and visual hierarchy. Output {{detail}} notes and a reproducible shot brief. Describe only observable features.',
    [select('detail', 'Detail level', ['concise', 'detailed', 'production notes'])], { tags: ['experimental', 'analysis'] }),
  template('motion-tracker', 'Motion Tracker', 'Blob Tracking', 'experimental', 'crosshair', '#b6d5ca',
    'Prepare a tracking and overlay workflow for a clearly specified subject.',
    'Prepare an editor tracking plan for {{subject}} in selected footage. Overlay: {{overlay}}. Flag occlusion or low-confidence moments for review. Do not claim tracking has run until the editor has produced it.',
    [text('subject', 'Track subject', 'the main moving object'), select('overlay', 'Overlay', ['label', 'trail', 'outline'])], { studioMode: 'editor' }),
  template('depth-motion', 'Depth Motion', 'DepthWarp4D', 'experimental', 'layers', '#b2c4df',
    'Turn a still composition into a subtle layered-depth motion brief.',
    'Animate the selected still with {{depth}} depth movement and a {{camera}} camera. Preserve subject edges, fill newly revealed areas plausibly and avoid excessive warping.',
    [select('depth', 'Depth strength', ['subtle', 'medium']), camera()], { studioMode: 'video' }),
  template('camera-stage', 'Camera Stage', 'Webcam Set', 'experimental', 'video', '#d0c49c',
    'Plan a virtual set using an explicitly selected camera still or image reference.',
    'Design a virtual set for the selected camera reference. Set: {{set}}. Lighting: {{lighting}}. Preserve subject proportions and reserve foreground space. Camera access is not requested by this recipe.',
    [text('set', 'Set idea', 'a cozy creative workshop'), select('lighting', 'Lighting', ['soft daylight', 'studio key light', 'warm practical lights'])]),
  template('glitch-cut', 'Glitch Cut', 'Datamosh', 'experimental', 'zap', '#d4b0c7',
    'Direct a controlled glitch treatment with subject readability and no strobing.',
    'Prepare a {{effect}} glitch treatment for selected footage. Intensity: {{intensity}}. Avoid rapid flashing and preserve the key subject and original duration. Preview in Editor Studio.',
    [select('effect', 'Treatment', ['block displacement', 'colour trails', 'frame echoes']), select('intensity', 'Strength', ['subtle', 'medium'])], { studioMode: 'editor' }),
  template('model-turntable', 'Model Turntable', '3D Model Visualizer', 'experimental', 'box', '#acccda',
    'Prepare a product turntable concept from selected model renders or reference images.',
    'Create a turntable-shot concept for {{subject}} from selected references. Material: {{material}}. Camera: slow orbit. Keep geometry consistent. This recipe does not execute or import 3D model files.',
    [text('subject', 'Object', 'a sculptural product'), text('material', 'Surface finish', 'matte ceramic')], { studioMode: 'video' }),
  template('scene-scout', 'Scene Scout', 'Scout360', 'experimental', 'globe', '#b4d3b1',
    'Explore angles for a location concept with a coherent environmental brief.',
    'Develop a location scouting board for {{setting}}. Time: {{time}}. Include wide establishing view, medium composition and detail shot, maintaining the same architecture and lighting. Do not claim a captured 360 panorama.',
    [text('setting', 'Location', 'a quiet hillside town'), select('time', 'Time', ['morning', 'afternoon', 'night'])]),
  template('motion-pose', 'Motion Pose', 'Ribbit', 'experimental', 'activity', '#d3d5a7',
    'Direct expressive character poses and movement from your own references.',
    'Create a character movement study for {{action}}. Energy: {{energy}}. Preserve the selected character identity and maintain believable anatomy across poses.',
    [text('action', 'Movement', 'a joyful leap'), select('energy', 'Energy', ['gentle', 'animated', 'dynamic'])], { studioMode: 'video' }),
  template('scene-remix', 'Scene Remix', 'Whisk', 'experimental', 'shuffle', '#d5b69c',
    'Compose a subject, setting and style direction into a unified image.',
    'Compose the selected subject in {{setting}} with {{style}} direction. Preserve subject identity, unify lighting and perspective, and avoid an obvious pasted collage.',
    [text('setting', 'New setting', 'a colourful rooftop garden'), style()]),
  template('letter-pose', 'Letter Pose', 'Pose Text', 'experimental', 'type', '#dcb2c5',
    'Explore expressive letterforms and poses as a deliberate typographic concept.',
    'Create a typographic concept for {{text}}. Pose idea: {{pose}}. Visual direction: {{style}}. Keep the words readable and reserve clear margins.',
    [text('text', 'Word or phrase', 'HELLO'), text('pose', 'Shape or pose', 'playful sculptural letters'), style()]),
  template('face-performance', 'Face Performance', '3D Face Swap', 'experimental', 'smile', '#c4bce0',
    'Plan a consent-based stylized character expression study from selected references.',
    'Create a stylized expression study for the selected original character. Expression: {{expression}}. Preserve identity. Use only selected references the user is authorized to use. Do not portray real people saying or doing unprovided actions.',
    [select('expression', 'Expression', ['joy', 'curiosity', 'surprise', 'determination']), style()], { studioMode: 'character' }),
];
